export const cuisineList = [
    'American',
    'Asian',
    'Bakery',
    'Barbecue',
    'Breakfast',
    "BBQ",
    'Burgers',
    'Cafe',
    'Chinese',
    'Coffee & Tea',
    'Deli',
    'Desserts',
    'Fast Food',
    'Ice Cream',
    'Indian',
    'Italian',
    'Japanese',
    'Mediterranean',
    'Mexican',
    'Pizza',
    'Seafood',
    'Sushi',
    'Thai',
    'Vegetarian',
    'Vietnamese',
    "healthy",
    ];